version: '3.8'

services:
  bookstore1:
    build: .
    ports:
      - "8081:8080"
    networks:
      - app-network

  bookstore2:
    build: .
    ports:
      - "8082:8080"
    networks:
      - app-network

networks:
  app-network: